name: "Nix build"
on:
  pull_request:
  push:
  workflow_call:
jobs:
  nix-flake-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L

  startup-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: workflow/nix-shell-action@v3
      with:
        # flakes: .#
        packages: neovim
        script: |
          # Copy configs
          mkdir -p ~/.config/nvim
          cp -r ./* ~/.config/nvim
          # Bootstrap plugins
          nvim --headless -u ~/.config/nvim/init.lua +PackerSync +PackerCompile +q
          # Startup with plugins installed
          nvim --headless -u ~/.config/nvim/init.lua +q

  shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#devShells.x86_64-linux.default --print-build-logs

