name: "Nix build"
on:
  pull_request:
  push:
  workflow_call:
jobs:
  nix-flake-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L

  shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#devShells.x86_64-linux.default --print-build-logs

  nvim-startup-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Copy files
      run: |
        mkdir -p ~/.config/nvim
        cp -r ./* ~/.config/nvim
    - name: Bootstrap plugins
      run: nix shell -c nvim --headless -u ~/.config/nvim/init.lua +q
    - name: Startup with plugins installed
      run: nix shell -c nvim --headless -u ~/.config/nvim/init.lua +q
